Repository Arquisoft/dede_es1a, pull requests merged in 2022-05, with the labels that each got.

#194 Lógica para la creación de pedidos
  restapi/controllers/OrderController.ts
  webapp/src/api/api.ts
  webapp/src/components/payment/PaymentPage.tsx
  webapp/src/shared/shareddtypes.ts
Labels: backend

#197 Función para obtener el mas vendido
  restapi/api.ts
  restapi/controllers/OrderController.ts
Labels: backend

#204 Test de Carga
  webapp/loadtestexample/BuyProductSimulation.scala
  webapp/loadtestexample/GetCatalogSimulation.scala
  webapp/loadtestexample/GoToCheckOutSimulation.scala
  webapp/loadtestexample/LoginSimulation.scala
  webapp/loadtestexample/UseCatalogFiltersSimulation.scala
  webapp/loadtestexample/gotocheckoutsimulation/0005_request.html
  webapp/loadtestexample/gotocheckoutsimulation/0006_request.json
  webapp/loadtestexample/loginsimulation/0003_request.html
  webapp/loadtestexample/loginsimulation/0004_request.json
Labels: test

#208 Correcciones
  restapi/controllers/RockController.ts
  restapi/controllers/UserController.ts
  webapp/src/App.tsx
  webapp/src/components/payment/PaymentSummary.tsx
  webapp/src/components/solid-pods/GetPodAddress.tsx
Labels: backend, frontend

#210 Correcciones del punto 7 de la documentación
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/images/07_DeploymentView.png
Labels: documentation

#212 Jorge test
  webapp/src/components/payment/creditCardForm/CardForm.tsx
  webapp/src/components/tests/Shoppingcart.test.tsx
  webapp/src/components/tests/payment/CardForm.test.tsx
  webapp/src/components/tests/payment/PaymentComplete.test.tsx
  webapp/src/components/tests/payment/PaymentListItems.test.tsx
  webapp/src/components/tests/payment/PaymentPage.test.tsx
  webapp/src/components/tests/payment/PaymentPayForm.test.tsx
  webapp/src/components/tests/payment/PaymentShipping.test.tsx
  webapp/src/components/tests/payment/PaymentSummary.test.tsx
Labels: test

#213 Corrección Test y CI final
  .github/workflows/asw2122.yml
  restapi/controllers/RockController.ts
  restapi/controllers/UserController.ts
  restapi/server.ts
  restapi/tests/api.test.ts
  webapp/loadtestexample/BuyProductSimulation.scala
  webapp/loadtestexample/GetCatalogSimulation.scala
  webapp/loadtestexample/GoToCheckOutSimulation.scala
  webapp/loadtestexample/LoginSimulation.scala
  webapp/loadtestexample/UseCatalogFiltersSimulation.scala
  webapp/loadtestexample/gotocheckoutsimulation/0005_request.html
  webapp/loadtestexample/gotocheckoutsimulation/0006_request.json
  webapp/loadtestexample/loginsimulation/0003_request.html
  webapp/loadtestexample/loginsimulation/0004_request.json
Labels: test

#217 Jorge puesta final 🧑‍🔧
  webapp/src/components/payment/PaymentListItems.tsx
  webapp/src/components/payment/PaymentPage.tsx
  webapp/src/components/payment/PaymentPayForm.tsx
  webapp/src/components/payment/PaymentShipping.tsx
  webapp/src/components/payment/PaymentSummary.tsx
  webapp/src/components/payment/creditCardForm/CardForm.tsx
  webapp/src/components/solid-pods/GetPodAddress.tsx
  webapp/src/components/tests/payment/CardForm.test.tsx
  webapp/src/components/tests/payment/PaymentPage.test.tsx
  webapp/src/components/tests/payment/PaymentShipping.test.tsx
  webapp/src/components/tests/payment/PaymentSummary.test.tsx
Labels: frontend, test

#220 Hotfix Test restApi
  restapi/tests/api.test.ts
Labels: backend, test

#221 Versión final de la aplicación
  restapi/api.ts
  restapi/tests/api.test.ts
  webapp/e2e/features/add-cart.feature
  webapp/e2e/features/logout-form.feature
  webapp/e2e/steps/add-cart.steps.ts
  webapp/e2e/steps/logout-form.steps.ts
  webapp/e2e/steps/orders-form.steps.ts
  webapp/src/api/api.ts
  webapp/src/components/Catalog.tsx
  webapp/src/components/Filter.tsx
  webapp/src/components/NavigationBar.tsx
  webapp/src/components/Product.tsx
  webapp/src/components/ProductView.tsx
  webapp/src/components/Showcase.tsx
  webapp/src/components/Showcases.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/components/payment/PaymentListItems.tsx
  webapp/src/components/payment/PaymentPage.tsx
  webapp/src/components/payment/PaymentPayForm.tsx
  webapp/src/components/payment/PaymentShipping.tsx
  webapp/src/components/payment/PaymentSummary.tsx
  webapp/src/components/payment/creditCardForm/CardForm.tsx
  webapp/src/components/solid-pods/GetPodAddress.tsx
  webapp/src/components/tests/Welcome.test.tsx
  webapp/src/components/tests/payment/CardForm.test.tsx
  webapp/src/components/tests/payment/PaymentPage.test.tsx
  webapp/src/components/tests/payment/PaymentShipping.test.tsx
  webapp/src/components/tests/payment/PaymentSummary.test.tsx
  webapp/src/components/tests/product/Product.test.tsx
  webapp/src/components/tests/product/ProductView.test.tsx
  webapp/src/components/tests/showcases/Showcase.test.tsx
  webapp/src/components/tests/showcases/Showcases.test.tsx
  webapp/src/css/App.css
  webapp/src/css/BouncingText.css
  webapp/src/css/CartItem.css
  webapp/src/css/Catalog.css
Labels: backend, test

#222 Hotfix registro
  webapp/src/components/Register.tsx
Labels: frontend

#228 Update 11_technical_risks.adoc
  docs/11_technical_risks.adoc
Labels: documentation

#233 Ultimo Pull Request 😥
  docs/11_technical_risks.adoc
  webapp/public/images/interfaz/favicon.ico
  webapp/public/images/interfaz/logo192.png
  webapp/public/images/interfaz/logo512.png
  webapp/public/images/minerales/coal-anthracite-380.jpg
  webapp/public/images/minerales/gneiss.jpg
  webapp/public/images/minerales/hornfels.jpg
  webapp/public/images/minerales/lapis-spheres-and-rough.jpg
  webapp/public/images/minerales/marble.jpg
  webapp/public/images/minerales/muscovite-schist.jpg
  webapp/public/images/minerales/phyllite.jpg
  webapp/public/images/minerales/quartz-novaculite-505.jpg
  webapp/public/images/minerales/quartzite.jpg
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/code/Prefilters.tsx
  webapp/src/components/payment/PaymentPage.tsx
  webapp/src/components/titleUtil.tsx
Labels: done

#234 Penúltimo Pull Request 😥
  docs/06_runtime_view.adoc
Labels: done

#235 Ultimo Pull Request 😥
  docs/06_runtime_view.adoc
Labels: done

#237 Despligue Heroku
  webapp/Dockerfile
  webapp/Procfile
  webapp/server.ts
Labels: deployment
