Repository Arquisoft/dede_es1a, pull requests merged in 2022-04, with the labels that each got.

#118 Funcionalidad para Filtrado por criterio
  .gitignore
  restapi/controllers/RockController.ts
  restapi/controllers/UserController.ts
  restapi/package.json
  restapi/server.ts
  restapi/tests/api.test.ts
Labels: done, backend

#136 Documentación punto 9 y 7
  docs/07_deployment_view.adoc
  docs/09_design_decisions.adoc
  docs/12_glossary.adoc
Labels: documentation

#138 Jorge carrito
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/CartItem.tsx
  webapp/src/components/Catalog.tsx
  webapp/src/components/NavigationBar.tsx
  webapp/src/components/PaymentPage.tsx
  webapp/src/components/Product.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/components/Showcase.tsx
  webapp/src/components/Showcases.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/components/tests/Welcome.test.tsx
  webapp/src/css/CartItem.css
  webapp/src/css/PaymentPage.css
  webapp/src/css/ShoppingCart.css
  webapp/src/images/interfaz/carrito-de-compras.png
  webapp/src/shared/shareddtypes.ts
Labels: backend, frontend

#142 Añadido hoja estilos a Payment Page :information_desk_person:
  webapp/src/components/PaymentPage.tsx
  webapp/src/css/App.css
  webapp/src/css/PaymentPage.css
  webapp/src/css/ShoppingCart.css
Labels: frontend

#164 Corrección búsqueda por criterio
  restapi/.env
  restapi/api.ts
  restapi/controllers/OrderController.ts
  restapi/controllers/RockController.ts
  restapi/controllers/UserController.ts
  restapi/models/Order.ts
  restapi/tests/api.test.ts
Labels: backend

#165 Creación de orders y pruebas de la restapi
  restapi/controllers/OrderController.ts
  restapi/controllers/RockController.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
Labels: backend

#167 Actualización de la barra de navegación
  restapi/controllers/UserController.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Login.tsx
  webapp/src/components/NavigationBar.tsx
Labels: frontend

#176 Creada vista proceso de pagos y arreglados errores anteriores
  restapi/package-lock.json
  webapp/package-lock.json
  webapp/src/App.tsx
  webapp/src/components/CartItem.tsx
  webapp/src/components/PaymentPage.tsx
  webapp/src/components/Product.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/components/payment/PaymentComplete.tsx
  webapp/src/components/payment/PaymentItem.tsx
  webapp/src/components/payment/PaymentListItems.tsx
  webapp/src/components/payment/PaymentPage.tsx
  webapp/src/components/payment/PaymentPayForm.tsx
  webapp/src/components/payment/PaymentSummary.tsx
  webapp/src/components/solid-pods/LoginPod.tsx
  webapp/src/components/solid-pods/ProfileViewer.tsx
  webapp/src/css/App.css
  webapp/src/css/PaymentProcess.css
  webapp/src/css/ShoppingCart.css
Labels: frontend

#180 Unión Backend y Frontend LIsta pedidos
  restapi/api.ts
  restapi/controllers/OrderController.ts
  restapi/controllers/RockController.ts
  restapi/models/Order.ts
  webapp/src/api/api.ts
  webapp/src/components/NavigationBar.tsx
  webapp/src/components/OrderUser.tsx
  webapp/src/components/Orders.tsx
  webapp/src/shared/shareddtypes.ts
Labels: backend, frontend

#181 Despliegue de la aplicación
  .github/workflows/asw2122.yml
  docker-compose-deploy.yml
  restapi/controllers/UserController.ts
  restapi/server.ts
  restapi/tests/api.test.ts
  webapp/Dockerfile
  webapp/server.ts
  webapp/src/App.tsx
Labels: backend, deployment
